# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --production --ignore-scripts && \
    npm install typescript --no-save && \
    npm install @types/node --no-save

# Copy all files
COPY . .

# Build project
RUN npm run build

# Ensure binary is executable
RUN chmod +x build/client.js

# Expose no ports (stdio use)

# Default command
CMD ["node", "build/client.js"]
